name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            # Ensure app dir
            cd ~/app || mkdir -p ~/app && cd ~/app

            # Get latest code
            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/${{ github.repository }} . 
            fi

            # Stop and remove old container
            docker stop app || true
            docker rm app || true

            # Build and run Docker container
            docker build -t app .
            docker run -d -p 5000:5000 --name app app
          EOF
